name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Déclenche le workflow à chaque push sur la branche 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Utilise une machine Ubuntu pour exécuter le workflow

    steps:
      # Clone le dépôt
      - name: Checkout code
        uses: actions/checkout@v3  # Utilisation de la dernière version stable de actions/checkout

      # Configure Docker Buildx pour construire des images multi-plateformes
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Configure Docker Buildx pour les images multi-plateformes

      # Authentification à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Utilisation de la dernière version stable de login-action
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Utilisation des secrets GitHub pour l'authentification
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construction de l'image Docker
      - name: Build Docker image
        run: |
          docker build -t ykrim3/myapp:latest .  # Remplacez par votre nom d'utilisateur Docker Hub et le nom de votre image

      # Pousser l'image Docker sur Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ykrim3/myapp:latest  # Pousse l'image sur Docker Hub
