name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Déclenche le workflow à chaque push sur la branche 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Utilise une machine Ubuntu pour exécuter le workflow

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Clone le dépôt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Configure Docker Buildx pour construire des images multi-plateformes

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Authentification à Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Utilise les secrets GitHub pour éviter de stocker votre identifiant en clair
          password: ${{ secrets.DOCKER_PASSWORD }}  # Idem pour le mot de passe

      - name: Build Docker image
        run: |
          docker build -t yourdockerhubusername/yourimagename:latest .  # Crée une image Docker

      - name: Push Docker image to Docker Hub
        run: |
          docker push yourdockerhubusername/yourimagename:latest  # Pousse l'image sur Docker Hub
